name: GitHub Metrics
on:
  schedule: [{ cron: "0 0 * * *" }]
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Core Metrics
        uses: lowlighter/metrics@latest
        with:
          user: RaedAddala
          token: ${{ secrets.METRICS_SECRET }}
          filename: metrics.core.svg
          base: header, activity, community, repositories, metadata
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 10
          plugin_lines: yes
          config_timezone: Africa/Tunis
          config_order: base.header, base.activity, base.community, base.repositories, base.metadata, isocalendar, languages, lines
          config_padding: 6,12
          config_twemoji: yes
          optimize: yes

      - name: Extra Metrics
        uses: lowlighter/metrics@latest
        with:
          user: RaedAddala
          token: ${{ secrets.METRICS_SECRET }}
          filename: metrics.extra.svg
          base: ""
          plugin_activity: yes
          plugin_activity_limit: 8
          plugin_activity_days: 90
          plugin_activity_filter: all
          plugin_notable: yes
          plugin_notable_indepth: yes
          plugin_stars: yes
          plugin_stargazers: yes
          plugin_followup: yes
          plugin_topics: yes
          plugin_topics_mode: icons
          plugin_topics_limit: 15
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 11842805
          plugin_stackoverflow_sections: reputation, badges, answers-top, questions-top
          plugin_stackoverflow_limit: 4
          config_timezone: Africa/Tunis
          config_order: activity, followup, notable, stargazers, stars, topics, stackoverflow
          config_padding: 6,12
          config_twemoji: yes
          optimize: yes
